### ISSUE TITLE
How to backup more than 2 folders

### ISSUE THREAD

**Issue by kuyagic** [X-Ryl669/Frost#10]
the  `--backup`  param can only process one folder  

How can I backup both `/root` and `/opt` folder in a revision

**Comment by X-Ryl669** [comment]
As you've seen, you can't have 2 `--backup` parameter.

The 2 solutions I see are:

1. You backup `/` and use exclusion rules to exclude everything except `/root` and `/opt`, or simpler, exclude everything (`--exclude`) and re-include '/root' and `/opt` only in `--include` (so you don't need to list all item in `/`)
2. Make 2 successive backup (one in `/root`, the other in `/opt`). That's what I'm doing.

**Comment by X-Ryl669** [comment]
Thank you for your report.
