### ISSUE TITLE
Missing Timeout.hpp

### ISSUE THREAD

**Issue by pbtrung** [X-Ryl669/Frost#4]
`ClassPath/include/File/File.hpp` needs `ClassPath/include/Time/Timeout.hpp`, which is absent, so can not compile.

**Comment by X-Ryl669** [comment]
Can you pull the last version and check again ?
I've added missing files and updated the main library version so it should work now.

**Comment by pbtrung** [comment]
I still got the following errors but it might be my system configuration.

>  Compiling Frost.cpp
>  Compiling bstrlib.c
>  Compiling easyzlib.c
Linking build/Frost
build/./ClassPath/src/File/File.o: In function `File::Info::setMetaData(Bstrlib::String)':
File.cpp:(.text+0x3053): warning: lchmod is not implemented and will always fail
/usr/bin/ld: build/./ClassPath/src/Platform/Linux.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/lib/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:72: recipe for target 'build/Frost' failed
make: *** [build/Frost] Error 1

**Comment by X-Ryl669** [comment]
Can you replace line 63 of the Makefile to read: 

    SHAREDLIBS += -lrt -ldl

?

**Comment by pbtrung** [comment]
Thanks. It works now. Testing...
