### ISSUE TITLE
Bug: spaces in backup dir name

### ISSUE THREAD

**Issue by pbtrung** [X-Ryl669/Frost#6]
`./Frost --backup dir\ name --compression bsc --index index --remote remote --multichunk 10M`

`error: Bad argument for backup, the --backup parameter is not a folder`

**Comment by X-Ryl669** [comment]
Ok, track it down, it's a bug about how I'm using system's wordexp function to expand the user-given parameters.
Actually, it splits the directory name in 2 because there is a space between it. I'll commit a patch later today.

**Comment by pbtrung** [comment]
I still get the error
`./Frost --backup /path/to/dir\ name --compression bsc --index index --remote remote --multichunk 10M`

`error: Bad argument for backup, the --backup parameter is not a folder`

**Comment by X-Ryl669** [comment]
Here's what I'm doing:
```
$ cd Frost
$ make clean
[...]
$ git pull
[...]
$ make -j 3 CONFIG=Debug
[...]
Built Frost version: 419
$ mkdir dir\ name
$ rm -r index
$ rm -r remote
$ rm ~/.frost/keys
$ mkdir dir\ name
$ ./Frost --backup /path/to/dir\ name --compression bsc --index index --remote remote --multichunk 10M
Password:
Done

Backup: Finished: /path/to/Frost/dir name/, (source size: 0, backup size: 0, 0 files, 1 directories) [0/0]
```

**Comment by pbtrung** [comment]
It is really weird.
It failed on with `--backup /path/to/IE\ 552` but not on `/path/to/abc\ 123`or `/path/to/BC\ 123`

**Comment by pbtrung** [comment]
Oh. My bad. I do not have `IE\ 552` right now.
It works.
